<a href="https://colab.research.google.com/github/R-Kani/R-Kani/blob/main/Project_Based_Assignment_CLO_2_Kelompok_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>Project-Based Assignment CLO-2</center>

<b>Topik : </b>
Implementation of Supervised Learning on Regression Task

<b>Anggota Kelompok</b>
1. I Made Denis Maharditha - 1301210537
2. Putri Maharani - 1301213093
3. Ratin Kani - 1301213269

### Latar Belakang


---

Latar belakang proyek ini adalah upaya untuk memenuhi persyaratan Tugas Project-Based Assignment CLO-2 dalam mata kuliah Machine Learning. Proyek ini mendorong penerapan konsep pembelajaran mesin dalam pemecahan masalah dunia nyata dengan fokus pada metode Support Vector Machine (SVM) untuk tugas regresi. Regresi adalah konsep fundamental dalam machine learning yang memungkinkan untuk memprediksi hasil berdasarkan variabel input. Dalam proyek ini dataset yang diekplorasi adalah  "Seoul Bike Sharing Demand” yang dapat diakses melalui https://archive.ics.uci.edu/dataset/560/seoul+bike+sharing+demand. Proyek ini bertujuan untuk memanfaatkan teknologi machine learning guna memahami dan meramalkan permintaan sepeda berdasarkan faktor-faktor seperti kondisi cuaca meliputi musim, suhu, kelembapan, kecepatan angin, jarak pandang, suhu titik embun, radiasi matahari, curah hujan, dan salju. Serta faktor waktu yang meliputi jam, hari libur, dan hari kerja.  Dengan tujuan ini, diharapkan akan memperdalam pemahaman tentang machine learning, menerapkan teknik regresi melalui SVM, melakukan pra-pemrosesan data untuk mengoptimalkan kualitas dataset, serta melakukan eksplorasi untuk memahami pola-pola dalam data dengan menciptakan beberapa model dengan variasi parameter guna menentukan model terbaik yang dapat mengatasi tugas regresi ini secara efisien. Dengan demikian, tugas ini tidak hanya memenuhi persyaratan mata kuliah Machine Learning tetapi juga memberikan kesempatan berharga untuk menguasai penggunaan metode SVM dalam konteks pemodelan regresi untuk aplikasi dunia nyata, seperti pengelolaan penyewaan sepeda di kota Seoul.

### Data Preprocessing dan Eksplorasi Data
 Proses membersihkan, merapikan, dan mempersiapkan data mentah untuk analisis, serta tahap awal untuk memahami dan identifikasi pola data

#### Import Library


In [ ]:
import numpy as np
import pandas as pd

#### Import Dataset

In [ ]:
dataset = pd.read_csv('SeoulBikeData.csv', encoding='latin1')
X = dataset.iloc[:, 2:].values
Y = dataset.iloc[:, 1].values

Menampilkan beberapa baris pertama dari X

In [ ]:
print("Head of X:")
print(X[:5, :])

Head of X:
[[0 -5.2 37 2.2 2000 -17.6 0.0 0.0 0.0 'Winter' 'No Holiday' 'Yes']
 [1 -5.5 38 0.8 2000 -17.6 0.0 0.0 0.0 'Winter' 'No Holiday' 'Yes']
 [2 -6.0 39 1.0 2000 -17.7 0.0 0.0 0.0 'Winter' 'No Holiday' 'Yes']
 [3 -6.2 40 0.9 2000 -17.6 0.0 0.0 0.0 'Winter' 'No Holiday' 'Yes']
 [4 -6.0 36 2.3 2000 -18.6 0.0 0.0 0.0 'Winter' 'No Holiday' 'Yes']]


Menampilkan beberapa baris pertama dari Y

In [ ]:
print("Head of Y:")
print(Y[:5])

Head of Y:
[254 204 173 107  78]


#### Pengkodean Variabel Independen

##### Mengubah variabel kategorikal atau label menjadi bilangan bulat
Untuk Kolom Ke-10, Keterangan "No Holiday" menjadi 0, dan "Holiday" menjadi 1

Untuk Kolom Ke-11, Keterangan "No" menjadi 0, dan "Yes" menjadi 1


In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:, 10] = 1-le.fit_transform(X[:, 10])
X[:, 11] = le.fit_transform(X[:, 11])

Menampilkan beberapa baris pertama dari X Setelah dilakukan LabelEncoder

In [ ]:
print("Head of X:")
print(X[:5, :])

Head of X:
[[0 -5.2 37 2.2 2000 -17.6 0.0 0.0 0.0 'Winter' 0 1]
 [1 -5.5 38 0.8 2000 -17.6 0.0 0.0 0.0 'Winter' 0 1]
 [2 -6.0 39 1.0 2000 -17.7 0.0 0.0 0.0 'Winter' 0 1]
 [3 -6.2 40 0.9 2000 -17.6 0.0 0.0 0.0 'Winter' 0 1]
 [4 -6.0 36 2.3 2000 -18.6 0.0 0.0 0.0 'Winter' 0 1]]


Mengubah variabel kategorikal menjadi representasi one-hot encoding, dimana setiap kategori diubah menjadi kolom terpisah dengan nilai 1 menunjukkan kehadiran kategori tersebut dan nilai 0 menunjukkan ketidakhadiran kategori tersebut

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

Menampilkan beberapa baris pertama dari X Setelah dilakukan OneHotlEncoder

In [ ]:
print("Head of X:")
print(X[:5, :])

Head of X:
[[0.0 0.0 0.0 1.0 0 -5.2 37 2.2 2000 -17.6 0.0 0.0 0.0 0 1]
 [0.0 0.0 0.0 1.0 1 -5.5 38 0.8 2000 -17.6 0.0 0.0 0.0 0 1]
 [0.0 0.0 0.0 1.0 2 -6.0 39 1.0 2000 -17.7 0.0 0.0 0.0 0 1]
 [0.0 0.0 0.0 1.0 3 -6.2 40 0.9 2000 -17.6 0.0 0.0 0.0 0 1]
 [0.0 0.0 0.0 1.0 4 -6.0 36 2.3 2000 -18.6 0.0 0.0 0.0 0 1]]


#### Memisahkan Dataset Menjadi Data Latih (Training Set) dan Data Uji (Test Set)

Membagi dataset menjadi dua bagian, yaitu data pelatihan (X_train dan Y_train) dan data pengujian (X_test dan Y_test) , yang dalam kasus ini, dataset akan dibagi menjadi data pelatihan (75%) dan data pengujian (25%).

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

#### Penskalaan Fitur (Feature Scaling)

Melakukan penskalaan fitur sehingga rerata (mean) sekitar 0 dan simpangan baku (standard deviation) sekitar 1

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Menampilkan beberapa baris pertama dari X_train dan X_test Setelah dilakukan Feature Scaling

In [ ]:
print("Head of X_train:")
print(X_train[:5, :])

print("\nHead of X_test:")
print(X_test[:5, :])

Head of X_train:
[[ 1.72819284 -0.5807482  -0.57582707 -0.57418668  1.66765533 -0.74954694
   1.22697808 -0.60031734 -1.72479535 -0.21606478 -0.65549033 -0.12622668
   0.75014943 -0.23069934  0.17946416]
 [-0.57863913  1.72191666 -0.57582707 -0.57418668  0.36544652  0.93615918
  -0.54181953  0.55489426 -1.51110252  0.60963914  2.63117329 -0.12622668
  -0.17270082 -0.23069934  0.17946416]
 [-0.57863913 -0.5807482  -0.57582707  1.74159386  1.08889586 -1.65916064
  -1.22968527  0.26609136  0.73595975 -1.87511801 -0.65549033 -0.12622668
  -0.17270082 -0.23069934  0.17946416]
 [-0.57863913  1.72191666 -0.57582707 -0.57418668  0.07606679 -0.04021516
   1.91484382 -0.88912024 -1.97465158  0.60199373 -0.49516527  1.59826753
  -0.17270082 -0.23069934  0.17946416]
 [ 1.72819284 -0.5807482  -0.57582707 -0.57418668 -1.08145215 -0.7662371
   0.58824561 -0.88912024  0.81321793 -0.39955453 -0.65549033 -0.12622668
  -0.17270082 -0.23069934  0.17946416]]

Head of X_test:
[[-5.78639130e-01  1.72191666e+

### Ringkasan Metode


---



Metode yang digunakan dalam tugas ini adalah Support Vector Machine for Regression (SVR), sebuah pendekatan yang sangat efektif untuk tugas regresi. SVR berfokus pada pencarian garis regresi yang optimal dengan tujuan meminimalkan deviasi antara titik data sebanyak mungkin, sambil mempertimbangkan toleransi kesalahan yang dapat diterima. Tahapan implementasi SVR mencakup pra-pemrosesan, eksplorasi data, pembangunan model baseline dimana merupakan sebuah model pelatihan sederhana dengan parameter-parameter default, dan tidak melibatkan tuning atau kompleksitas tambahan. Dilanjutkan dengan eksplorasi Model dengan membangun beberapa skema model melalui proses hyperparameter tuning atau pemilihan kombinasi parameter yang bervariasi melalui validasi silang (cross-validation) untuk mengidentifikasi kernel dan nilai parameter C yang menghasilkan model SVR dengan kinerja terbaik dalam memprediksi nilai target. Evaluasi model dilakukan dengan metrik seperti Mean Absolute Error (MAE) dan R-Square (R²), yang memberikan pandangan tentang seberapa baik model ini memodelkan hubungan antara variabel input, seperti cuaca dan waktu, dengan permintaan sepeda dalam dataset Seoul Bike Sharing Demand.



### Pembangunan Model Baseline
Pembuatan model yang sederhana dengan parameter-parameter default, dan tidak melibatkan tuning atau kompleksitas tambahan.

In [ ]:
class linearKernel:
    # Konstruktor inisialisasi parameter-model dan atribut
    def __init__(self, C=1.0, epsilon=0.1, max_iterations=1000, learning_rate=0.01):
        self.C = C  # Parameter regulasi SVR
        self.epsilon = epsilon  # Toleransi kesalahan
        self.max_iterations = max_iterations  # Jumlah iterasi maksimum
        self.learning_rate = learning_rate  # Laju pembelajaran
        self.alpha = None  # Bobot alpha dari model
        self.X_train = None  # Data pelatihan
        self.weights = None  # Bobot yang akan dihitung selama pelatihan
        self.bias = None  # Bias yang akan dihitung selama pelatihan

    # Fungsi kernel linear untuk menghitung kesamaan antara dua vektor
    def linear_kernel(self, xi, xj):
        return np.dot(self.weights, xi) * np.dot(self.weights, xj)

    # Melatih model SVR dengan kernel linear
    def fit(self, X, y):
        self.X_train = X
        n_samples, n_features = X.shape
        self.alpha = np.zeros(n_samples)
        self.weights = np.ones(n_features)
        self.bias = 0

        # Inisialisasi matriks kernel K
        K = np.zeros((n_samples, n_samples))

        # Mengisi matriks kernel K dengan nilai-nilai kernel linear antara pasangan data pelatihan
        for i in range(n_samples):
            for j in range(n_samples):
                K[i, j] = self.linear_kernel(X[i], X[j])

        # Iterasi pelatihan model SVR dengan kernel linear
        for _ in range(self.max_iterations):
            for i in range(n_samples):
                error = y[i] - (np.dot(self.alpha, K[i]) + self.bias)

                # Update bobot (weights) dan bias berdasarkan error
                if error < -self.epsilon: # Kodisi jika error di bawah -epsilon
                    self.weights += self.learning_rate * (2 * self.C * (y[i] - np.dot(X[i], self.weights) - self.bias) * X[i] - self.weights)
                    self.bias += self.learning_rate * 2 * self.C * (y[i] - np.dot(X[i], self.weights) - self.bias)
                elif error > self.epsilon: # Kodisi jika error di atas epsilon
                    self.weights += self.learning_rate * (2 * self.C * (y[i] - np.dot(X[i], self.weights) - self.bias) * X[i] - self.weights)
                    self.bias += self.learning_rate * 2 * self.C * (y[i] - np.dot(X[i], self.weights) - self.bias)

        return self

    # Membuat prediksi menggunakan model SVR yang sudah dilatih
    def predict(self, X_test):
      n_samples, _ = X_test.shape
      y_pred = np.zeros(n_samples)

      # Iterasi untuk menghitung prediksi untuk setiap sampel
      for i in range(n_samples):
        y_pred[i] = np.dot(X_test[i], self.weights) + self.bias
      return y_pred

Pelatihan model SVR dengan kernel linear yang telah implementasikan sebelumnya

In [ ]:
svr = linearKernel(C=0.1, epsilon=0.2, max_iterations=10, learning_rate=0.01)
svr.fit(X_train, Y_train)

Membuat prediksi pada data pengujian.

In [ ]:
Y_pred = svr.predict(X_test)

Mendefinisikan fungsi yang digunakan untuk menghitung metrik evaluasi kinerja model regresi, yaitu Mean Squared Error (MSE) dan R-squared (R²).

In [ ]:
# Hitung Mean Squared Error (MSE)
def mean_squared_error(y_true, y_pred):
    n = len(y_true)
    mse = sum((y_true[i] - y_pred[i]) ** 2 for i in range(n)) / n
    return mse

# Hitung R-squared (R²)
def r_squared(y_true, y_pred):
    n = len(y_true)
    mean_y = sum(y_true) / n
    ssr = sum((y_true[i] - y_pred[i]) ** 2 for i in range(n))
    sst = sum((y_true[i] - mean_y) ** 2 for i in range(n))
    r2 = 1 - (ssr / sst)
    return r2

Menampilkan hasil perhitungan MSE dan R² untuk Baseline Model




In [ ]:
mse = mean_squared_error(Y_test, Y_pred)
print("Mean Squared Error (MSE) Untuk Baseline Model :", mse)

r2 = r_squared(Y_test, Y_pred)
print("R-squared (R²) Untuk Baseline Model :", r2)

Mean Squared Error (MSE) Untuk Baseline Model : 313096.9025837174
R-squared (R²) Untuk Baseline Model : 0.24936565008280565


### Eksplorasi Model




####  Implementasi Kelas SVR Dengan Kernel RBF

In [ ]:
class rbfKernel:
    # Konstruktor inisialisasi parameter-model dan atribut
    def __init__(self, C=1.0, epsilon=0.1, max_iterations=1000, learning_rate=0.01, gamma=1.0):
        self.C = C  # Parameter regulasi SVR
        self.epsilon = epsilon  # Toleransi kesalahan
        self.max_iterations = max_iterations  # Jumlah iterasi maksimum
        self.learning_rate = learning_rate  # Laju pembelajaran
        self.gamma = gamma  # Parameter gamma untuk kernel RBF
        self.alpha = None  # Bobot alpha dari model
        self.X_train = None  # Data pelatihan
        self.weights = None  # Bobot yang akan dihitung selama pelatihan
        self.bias = None  # Bias yang akan dihitung selama pelatihan

    # Fungsi kernel RBF untuk menghitung kesamaan antara dua vektor
    def rbf_kernel(self, xi, xj):
        return np.exp(-self.gamma * np.linalg.norm(xi - xj) ** 2)

    # Melatih model SVR dengan kernel RBF
    def fit(self, X, y):
        self.X_train = X
        n_samples, n_features = X.shape
        self.alpha = np.zeros(n_samples)
        self.weights = np.ones(n_features)
        self.bias = 0

        # Inisialisasi matriks kernel K
        K = np.zeros((n_samples, n_samples))

        # Mengisi matriks kernel K dengan nilai-nilai kernel RBF antara pasangan data pelatihan
        for i in range(n_samples):
            for j in range(n_samples):
                K[i, j] = self.rbf_kernel(X[i], X[j])

        # Iterasi pelatihan model SVR dengan kernel RBF
        for _ in range(self.max_iterations):
            for i in range(n_samples):
                error = y[i] - (np.dot(self.alpha, K[i]) + self.bias)

                # Update bobot (weights) dan bias berdasarkan error
                if error < -self.epsilon: # Kodisi jika error di bawah -epsilon
                    self.weights += self.learning_rate * (self.alpha[i] * y[i] * self.rbf_kernel(X[i], X[i]) - self.alpha @ K[i])
                    self.bias += self.learning_rate * 2 * self.C * (y[i] - np.dot(X[i], self.weights) - self.bias)
                elif error > self.epsilon: # Kodisi jika error di atas epsilon
                    self.weights += self.learning_rate * (self.alpha[i] * y[i] * self.rbf_kernel(X[i], X[i]) - self.alpha @ K[i])
                    self.bias += self.learning_rate * 2 * self.C * (y[i] - np.dot(X[i], self.weights) - self.bias)

        return self

    # Membuat prediksi menggunakan model SVR yang sudah dilatih
    def predict(self, X_test):
        n_samples, _ = X_test.shape
        y_pred = np.zeros(n_samples)

        # Iterasi untuk menghitung prediksi untuk setiap sampel
        for i in range(n_samples):
            y_pred[i] = np.dot(X_test[i], self.weights) + self.bias
        return y_pred

####  Implementasi Kelas SVR Dengan Kernel Polynomial

In [ ]:
class polyKernel:
    # Konstruktor inisialisasi parameter-model dan atribut
    def __init__(self, C=1.0, epsilon=0.1, max_iterations=1000, learning_rate=0.01, degree=2):
        self.C = C  # Parameter regulasi SVR
        self.epsilon = epsilon  # Toleransi kesalahan
        self.max_iterations = max_iterations  # Jumlah iterasi maksimum
        self.learning_rate = learning_rate  # Laju pembelajaran
        self.degree = degree  # Derajat polinomial untuk kernel
        self.alpha = None  # Bobot alpha dari model
        self.X_train = None  # Data pelatihan
        self.weights = None  # Bobot yang akan dihitung selama pelatihan
        self.bias = None  # Bias yang akan dihitung selama pelatihan

    # Fungsi kernel polinomial untuk menghitung kesamaan antara dua vektor
    def poly_kernel(self, xi, xj):
        return (np.dot(xi, xj) + 1) ** self.degree

    # Melatih model SVR dengan kernel polinomial
    def fit(self, X, y):
        self.X_train = X
        n_samples, n_features = X.shape
        self.alpha = np.zeros(n_samples)
        self.weights = np.ones(n_features)
        self.bias = 0

        # Inisialisasi matriks kernel K
        K = np.zeros((n_samples, n_samples))

        # Mengisi matriks kernel K dengan nilai-nilai kernel polinomial antara pasangan data pelatihan
        for i in range(n_samples):
            for j in range(n_samples):
                K[i, j] = self.poly_kernel(X[i], X[j])

        # Iterasi pelatihan model SVR dengan kernel polinomial
        for _ in range(self.max_iterations):
            for i in range(n_samples):
                error = y[i] - (np.dot(self.alpha, K[i]) + self.bias)

                # Update bobot (weights) dan bias berdasarkan error
                if error < -self.epsilon: # Kodisi jika error di bawah -epsilon
                    self.weights += self.learning_rate * (2 * self.C * (y[i] - np.dot(X[i], self.weights) - self.bias) * X[i] - self.weights)
                    self.bias += self.learning_rate * 2 * self.C * (y[i] - np.dot(X[i], self.weights) - self.bias)
                elif error > self.epsilon: # Kodisi jika error di atas epsilon
                    self.weights += self.learning_rate * (2 * self.C * (y[i] - np.dot(X[i], self.weights) - self.bias) * X[i] - self.weights)
                    self.bias += self.learning_rate * 2 * self.C * (y[i] - np.dot(X[i], self.weights) - self.bias)

        return self

    def predict(self, X_test):
        n_samples, _ = X_test.shape
        y_pred = np.zeros(n_samples)

        # Iterasi untuk menghitung prediksi untuk setiap sampel
        for i in range(n_samples):
            y_pred[i] = np.dot(X_test[i], self.weights) + self.bias
        return y_pred

#### Hyperparameter tuning dengan metode grid search


---



Eksplorasi kombinasi hyperparameter untuk model Support Vector Regression (SVR) dengan berbagai jenis kernel, yaitu linear, rbf, dan polynomial dan nilai parameter C yaitu 0.1, 1.0, dan 3.0, dengan setiap kombinasi model SVR dilatih dan dievaluasi menggunakan teknik cross-validation atau dalam kasus ini, menggunakan 3-fold cross-validation

In [ ]:
# Definisikan grid parameter yang ingin diuji, termasuk berbagai jenis kernel
param_grid = {
    'kernel': ['linear', 'rbf', 'poly'],
    'C': [0.1, 1.0, 3.0],
}

# Jumlah fold dalam cross-validation
k = 3

best_kernel = None
best_C = None
best_mean_score = float('inf')

# Split data menjadi k bagian (fold)
fold_size = len(X_train) // k

for kernel in param_grid['kernel']:
    for C in param_grid['C']:
        scores = []
        for i in range(k):

            # Bagi data menjadi data pelatihan dan data validasi
            start = i * fold_size
            end = (i + 1) * fold_size
            X_val = X_train[start:end]
            Y_val = Y_train[start:end]
            X_train_fold = np.concatenate((X_train[:start], X_train[end:]))
            Y_train_fold = np.concatenate((Y_train[:start], Y_train[end:]))

            if kernel == 'linear':
                # Buat model SVR dengan kernel linear dan latih dengan data pelatihan
                svr = linearKernel(C=C, epsilon=0.2, max_iterations=1, learning_rate=0.01)
                svr.fit(X_train_fold, Y_train_fold)
            elif kernel == 'rbf':
                # Buat model SVR dengan kernel RBF dan latih dengan data pelatihan
                svr = rbfKernel(C=C, gamma=0.1, epsilon=0.2, max_iterations=1, learning_rate=0.01)
                svr.fit(X_train_fold, Y_train_fold)
            elif kernel == 'poly':
                # Buat model SVR dengan kernel polinomial dan latih dengan data pelatihan
                svr = polyKernel(C=C, epsilon=0.2, max_iterations=1, learning_rate=0.01)
                svr.fit(X_train_fold, Y_train_fold)

            # Lakukan prediksi pada data validasi
            Y_pred = svr.predict(X_val)

            # Hitung Mean Squared Error (MSE) untuk validasi
            mse = mean_squared_error(Y_val, Y_pred)
            print(f"Kernel: {kernel}, C: {C}, Fold: {i + 1}, MSE: {mse}")

            scores.append(mse)

        # Hitung rata-rata skor di seluruh fold
        mean_score = np.mean(scores)
        print(f"Rata - rata score: {mean_score}")

        # Periksa apakah ini adalah kombinasi kernel dan C terbaik sejauh ini
        if mean_score < best_mean_score:
            best_mean_score = mean_score
            best_kernel = kernel
            best_C = C

print("Kernel terbaik:", best_kernel)
print("Nilai C terbaik:", best_C)


Kernel: linear, C: 0.1, Fold: 1, MSE: 304863.89245975233
Kernel: linear, C: 0.1, Fold: 2, MSE: 305519.1595831723
Kernel: linear, C: 0.1, Fold: 3, MSE: 307857.76819647825
Rata - rata score: 306080.2734131343
Kernel: linear, C: 1.0, Fold: 1, MSE: 212543.77460390184
Kernel: linear, C: 1.0, Fold: 2, MSE: 210423.30640325756
Kernel: linear, C: 1.0, Fold: 3, MSE: 244347.68593778423
Rata - rata score: 222438.25564831457
Kernel: linear, C: 3.0, Fold: 1, MSE: 321697.3212948815
Kernel: linear, C: 3.0, Fold: 2, MSE: 310314.0689813253
Kernel: linear, C: 3.0, Fold: 3, MSE: 423485332.97341436
Rata - rata score: 141372448.12123019
Kernel: rbf, C: 0.1, Fold: 1, MSE: 411423.5104657404
Kernel: rbf, C: 0.1, Fold: 2, MSE: 413639.61254340014
Kernel: rbf, C: 0.1, Fold: 3, MSE: 416457.35565282474
Rata - rata score: 413840.15955398843
Kernel: rbf, C: 1.0, Fold: 1, MSE: 412288.20457607775
Kernel: rbf, C: 1.0, Fold: 2, MSE: 414599.3430737152
Kernel: rbf, C: 1.0, Fold: 3, MSE: 418724.30799537577
Rata - rata score

### Evaluasi

Pelatihan model SVR dengan kernel linear dan nilai C terbaik yang sudah didapatkan sebelumnya

In [ ]:
if best_kernel == 'linear':
  best_model = linearKernel(C=best_C, epsilon=0.2, max_iterations=10, learning_rate=0.01)
  best_model.fit(X_train, Y_train)
elif best_kernel == 'rbf':
  best_model = rbfKernel(C=best_C, gamma=0.1, epsilon=0.2, max_iterations=10, learning_rate=0.01)
  best_model.fit(X_train, Y_train)
elif best_kernel == 'poly':
  best_model = polyKernel(C=best_C, epsilon=0.2, max_iterations=10, learning_rate=0.01)
  best_model.fit(X_train, Y_train)

Membuat prediksi pada data pengujian dengan model dengan kernel dan nilai C terbaik

In [ ]:
best_Y_pred = best_model.predict(X_test)

Menampilkan hasil perhitungan MSE dan R² untuk model terbaik




In [ ]:
mse = mean_squared_error(Y_test, best_Y_pred)
print("Best Model Mean Squared Error (MSE):", mse)

r2 = r_squared(Y_test, best_Y_pred)
print("Best Model R-squared (R²):", r2)

Visualisasi hasil prediksi dari Model SVR dengan kernel linear dan C = 1.0

In [ ]:
import matplotlib.pyplot as plt

# Membuat plot scatter Actual vs. Predicted
plt.figure(figsize=(8, 6))
plt.scatter(Y_test, Y_pred, c='b', label="Actual vs. Predicted")
plt.plot([min(Y_test), max(Y_test)], [min(Y_test), max(Y_test)], 'k--', lw=2, label="Regression Line")
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.title("SVR: Actual vs. Predicted")
plt.legend()

# Menghitung dan membuat plot residual
residuals = Y_test - Y_pred
plt.figure(figsize=(8, 3))
plt.scatter(range(len(residuals)), residuals, c='r', label="Residuals")
plt.axhline(y=0, color='k', linestyle='--', lw=2, label="Residuals Mean")
plt.xlabel("Data Points")
plt.ylabel("Residuals")
plt.title("Residual Plot")
plt.legend()

# Menampilkan plot
plt.show()

### Hasil dan Analisis


---



#### Hasil
Hasil dari program ini adalah kombinasi terbaik dari kernel dan nilai parameter C untuk model SVR yang diuji serta hasil evaluasi model dengan kombinasi parameter terbaik tersebut dengan metrik evaluasi Mean Squared Error (MSE) dan R-Squared (R²). Kombinasi terbaik ini dipilih berdasarkan rata-rata hasil MSE pada setiap fold atau lipatan yang dihitung selama validasi silang (3-fold cross validation). Melalui validasi silang tersebut didapatkan kernel terbaik yang dipilih adalah "Kernel Linear" dengan nilai parameter C terbaik yang dipilih adalah C = 1. Kemudian berdasarkan hasil kombinasi tersebut dilakukan pelatihan model dengan menerapkan hasil dari kernel terbaik serta nilai parameter C  yang mendapatkan hasil MSE sebesar 218810.4968681095 dan hasil R² sebesar 0.4754126479174141.

#### Analisis


*   Kernel Linear dipilih sebagai kernel terbaik, yang merupakan salah satu kernel yang paling sederhana dalam metode Support Vector Regression (SVR).  Ini mengasumsikan bahwa hubungan antara fitur dan target adalah linier atau kerapatan data sekitar garis lurus. Ini berarti bahwa model SVR dengan kernel linear dapat memadai dalam menjelaskan pola hubungan yang bersifat linier antara fitur dan target.
*   Nilai C yang terbaik adalah 1, dimana parameter C mengontrol trade-off antara kesalahan pelatihan dan kompleksitas model. Nilai C yang lebih tinggi mengarah pada model yang lebih kompleks dengan penalti kesalahan pelatihan yang lebih tinggi, sementara nilai C yang lebih rendah mengarah pada model yang lebih sederhana dengan penalti kesalahan pelatihan yang lebih rendah. Nilai C = 1 dipilih sebagai yang terbaik, yang mungkin adalah kompromi yang baik antara kompleksitas model dan akurasi prediksi.
*   Hasil pelatihan model SVR dengan kernel linear dan nilai C terbaik menghasilkan MSE sebesar 218810.4968681095, dimana hasil ini masih dapat diinterpretasikan secara positif sebagai indikasi bahwa model mampu memprediksi data dengan akurasi yang cukup memadai walau masih memiliki kesalahan prediksi yang signifikan.
*   Hasil R² sebesar 0.4754126479174141, ini menunjukkan bahwa model SVR ini mampu menjelaskan sekitar 47,5% dari variabilitas dalam data. Ini adalah indikasi bahwa model masih memberikan kontribusi yang signifikan dalam menjelaskan hubungan antara fitur dan label.







#### Kesimpulan


---


Berdasarkan hasil dan analisis yang telah dilakukan dalam proyek ini, kesimpulan utama adalah pemilihan kombinasi terbaik antara kernel dan nilai parameter C untuk model Support Vector Regression (SVR). Hasil tersebut menunjukkan bahwa "Kernel Linear" merupakan pilihan terbaik, mengindikasikan bahwa hubungan antara variabel input, seperti cuaca dan waktu, dengan permintaan sepeda cenderung linier atau terdistribusi secara linear. Nilai parameter C terbaik adalah 1, menciptakan sebuah model dengan kompleksitas yang seimbang dan penalti kesalahan pelatihan yang moderat. Dengan menggunakan kombinasi ini, kita mencapai hasil Mean Squared Error (MSE) sebesar 218810.4968681095 dan R-squared (R²) sebesar 0.4754126479174141, yang menunjukkan bahwa model dengan kemampuan memadai dalam memodelkan hubungan antara variabel input dan permintaan sepeda dalam dataset.